# Generated by Django 5.1.7 on 2025-03-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Paramètre du site', 'verbose_name_plural': 'Paramètre du site'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_todo_items',
            field=models.PositiveIntegerField(),
        ),
    ]
