# Generated by Django 5.1.7 on 2025-03-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todoitemcomment_todo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemcomment',
            name='todo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo.todoitem'),
        ),
    ]
